roles:
  name: '角色与权限'
  operations:
    read: '查看'
    create: '新建'
    update: '更新'
    destroy: '删除'
users:
  name: '用户'
  operations:
    read: '查看'
    dashboard: '面板'
    create: '新建'
    update: '更新'
    destroy: '删除'
